### ISSUE TITLE
Missing route zone Uldum

### ISSUE THREAD

**Issue by ShawnDFox** [Nevcairiel/Routes#17]
### Description

while trying to create a route for the zone "uldum" the zone doesnt show up in the Select zone selectable, being in the zone dosnt auto select it eather.

### Routes Version

v1.8.1

### World of Warcraft Version

Retail (Default)

### Testing Isolation

- [X] No
- [ ] Yes, without any related optional dependencies.
- [ ] Yes, with related optional dependencies.

### Reproduction Steps

Using gathermate go to zone Uldum
try to generate a route after gathering some elementium nodes

### Screenshots

![imagen](https://github.com/Nevcairiel/Routes/assets/34876076/ceb6b566-40bb-4705-97a4-6c2b09550448)

**Comment by ShawnDFox** [comment]
This is also true for the valley of eternal blossoms, which makes it obvious its due to the void attack that happened in BFA, while gathermate is able to have data for the assault and the original zone separated looks like routes doesnt understand how it works

**Comment by karpana** [comment]
I'm noticing the same thing for "The Forbidden Reach", I can't select it as a zone in which to create a new route.

![image](https://github.com/Nevcairiel/Routes/assets/15716173/be52c178-aee3-46fd-a086-6b52ca8b3f6f)
![image](https://github.com/Nevcairiel/Routes/assets/15716173/d873fbd2-ebae-4ba7-9da9-1d393b1d19b4)
![image](https://github.com/Nevcairiel/Routes/assets/15716173/e93e3f56-829b-45eb-afb9-835c2a74dd91)

**Comment by adrnde** [comment]
Can verify - Uldum is missing from drop-down *while Black Empire invasion in progress*.   I tried talking to Zidormi to swap from Black Empire invasion mode to normal -- still no listing, until I did a /reload.
Black Empire version: map #1527
Cataclysm version: map #249
Once I added a Black Empire route, Uldum started showing up; not sure which.
