### ISSUE TITLE
[ISSUE] - New routes are invisible unless editing

### ISSUE THREAD

**Issue by SirJorb** [Nevcairiel/Routes#20]
### Description

Adding new routes, the line for the route doesn't appear unless in edit mode. 

### Routes Version

v1.8.2

### World of Warcraft Version

Retail (Default)

### Testing Isolation

- [x] No
- [X] Yes, without any related optional dependencies.
- [x] Yes, with related optional dependencies.

### Lua Error(s)

```true
None
```

### Reproduction Steps

Create new route from data source, such as Handynotes or Gathermate. There is no line on the route.

Notably bare routes work fine, but that means that you have to make routes entirely manually with no importing waypoints or optimizing.

### Last Known Good Version

Unsure

### Screenshots

![image](https://github.com/Nevcairiel/Routes/assets/23423782/005faad4-d057-4560-9fa5-2d087adaed2a)
![image](https://github.com/Nevcairiel/Routes/assets/23423782/d16342c1-06fa-46e8-ae94-43bec3b03b57)

**Comment by SirJorb** [comment]
Been almost 2 months and this still doesn't work. It basically renders the addon nearly non-functional...

**Comment by Nevcairiel** [comment]
I have created a variety of new routes just now, ind old and new zones, and they show just fine. It sounds to me like you have some kind of Auto Show configured that just hides the route.
